-- phpMyAdmin SQL Dump
-- version 5.1.1
-- https://www.phpmyadmin.net/
--
-- Хост: 127.0.0.1:3306
-- Время создания: Янв 22 2022 г., 18:35
-- Версия сервера: 8.0.24
-- Версия PHP: 8.0.14

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- База данных: `laravel`
--

-- --------------------------------------------------------

--
-- Структура таблицы `migrations`
--

CREATE TABLE `migrations` (
  `id` int UNSIGNED NOT NULL,
  `migration` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `batch` int NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Дамп данных таблицы `migrations`
--

INSERT INTO `migrations` (`id`, `migration`, `batch`) VALUES
(1, '2019_12_14_000001_create_personal_access_tokens_table', 1),
(2, '2022_01_21_155051_create_news_table', 1);

-- --------------------------------------------------------

--
-- Структура таблицы `news`
--

CREATE TABLE `news` (
  `id` bigint UNSIGNED NOT NULL,
  `title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `about` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `text` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `picture` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `city` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `favorite` tinyint(1) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Дамп данных таблицы `news`
--

INSERT INTO `news` (`id`, `title`, `about`, `text`, `picture`, `city`, `favorite`, `created_at`, `updated_at`) VALUES
(1, 'Omnis consequatur a delectus aut iste.', 'Laborum laudantium et recusandae voluptatem rerum esse ut saepe est magnam numquam at earum mollitia soluta consequatur et omnis molestiae doloribus est aut in totam voluptate et labore.', 'Et qui pariatur ut tempore nemo atque veritatis. Explicabo et tenetur minima harum repellat quisquam iste dicta. Libero voluptatem sint vero voluptate ducimus culpa saepe. Saepe vel repellendus facilis cum. Saepe soluta aut eius eligendi vel. Quam et unde voluptates porro ex molestias eos. Laboriosam quaerat quidem a quae. Doloribus sed iusto quia eum qui sed soluta. Consequuntur facere qui esse a veritatis eveniet eum. Quia voluptatem occaecati sapiente dolorem. Qui assumenda hic sit voluptatem molestias autem. Fugiat labore dolor ullam ducimus quia. Illum esse provident consectetur qui. Consectetur molestiae libero maiores veniam numquam. Quia enim ab dignissimos rerum. Et cum accusamus voluptatem id at aut tempora laudantium. Voluptatem commodi et qui numquam beatae unde. Saepe est officiis at modi laudantium aut. Quos nobis aspernatur quis laboriosam mollitia unde dolores. Officia consequatur laborum odio quod. Voluptatum rerum officiis necessitatibus minus labore odit modi. Quibusdam ullam aliquid quae quia reprehenderit eum. Hic rerum blanditiis provident consequuntur. Suscipit aut et aut. Dolorem cum et beatae. Minima quaerat molestias minus omnis cupiditate voluptatibus dolorum. Molestiae officia laudantium qui autem. Iure sed omnis officia et non commodi. Ipsa quia sapiente id voluptatum. Possimus perspiciatis illum atque. Perspiciatis est repellendus explicabo at ut necessitatibus doloremque. Et odit excepturi et enim sit et suscipit reprehenderit. Hic earum illo tempore dolores aut sit consequatur. Beatae dolorem molestiae ut aut. Molestiae est et repellat omnis rem. Nulla fuga esse recusandae autem.', '2.png', '', 1, '2022-01-22 10:49:33', '2022-01-22 10:49:33'),
(2, 'Quas omnis aut voluptatibus.', 'Provident ex velit ipsum recusandae voluptatem excepturi et possimus perspiciatis sunt aspernatur non delectus magni exercitationem dolorem rerum debitis qui dolorem occaecati consectetur esse.', 'Quia deleniti dolorem molestias modi atque vel. Dolorem fugiat incidunt saepe fugiat unde incidunt sit assumenda. Est autem fugit neque perferendis. Quo cumque non cum ea dolorem libero voluptatem. Autem rerum rem distinctio tempore repellendus quis eveniet. Ullam mollitia totam ullam deserunt quia dolores qui. Magni ea recusandae non velit ea. Laboriosam totam veniam rem est itaque dolorem. Velit illo est illo explicabo magni voluptas. Optio illo consectetur quod tempore qui et omnis. Doloribus harum aspernatur sunt necessitatibus. Consectetur aut dolores repellat maxime minima. In eos rem sequi quia. Sint consectetur maiores consequatur ab cupiditate aut. Voluptas et voluptas voluptas molestiae ut magni qui. Voluptates eum expedita impedit est. Nisi consequuntur id consectetur qui non ullam. Voluptatem corrupti nulla magni placeat omnis excepturi ut. Omnis porro quos qui quia soluta. Cupiditate quaerat quo et.', '5.png', 'moscow', 1, '2022-01-22 10:49:34', '2022-01-22 10:49:34'),
(3, 'Cum id eaque.', 'Quo odio corrupti et quia molestiae voluptatem dignissimos voluptate excepturi dolor iure et ipsa impedit optio consequatur consequatur at.', 'Amet qui quasi perspiciatis. Velit neque sint tempora in reprehenderit. Animi delectus quia accusantium quas. Deserunt molestias vero voluptate a. Culpa ut impedit delectus nihil voluptates repellendus quod autem. Dolorum in excepturi beatae minima nulla. Minus animi sit ut asperiores ut perspiciatis. Nihil voluptatibus quas voluptatum nisi voluptatem in molestias. Aliquam quibusdam suscipit ut dolore non. Sint fuga laboriosam doloremque fugit veniam officiis. Velit error tempore adipisci. Nam ex ut in quia. Quibusdam molestiae quia ut quam odio praesentium earum. In accusamus natus aut illo modi quaerat nisi. Voluptatem rerum magni perferendis et provident quo. Eum eos quo aut inventore. Delectus temporibus consequatur fugit pariatur veniam cupiditate dignissimos. Possimus explicabo dicta perferendis et soluta voluptates beatae. Et officia quam eum quas. Et natus voluptate in exercitationem ea possimus culpa voluptatem. Ut tenetur aut quis reiciendis. Earum provident quam magni et aut. Officiis cupiditate optio omnis voluptates temporibus sequi. Voluptates dolor pariatur quia accusantium saepe saepe enim unde. Est nam at et tempora odio distinctio sit. Qui natus consequatur ullam dolorum quia magni fugit. Dolor quia veritatis quos praesentium et nihil nostrum. Iste occaecati blanditiis aut maiores.', '4.png', 'nalchik', 1, '2022-01-22 10:49:34', '2022-01-22 10:49:34'),
(4, 'Natus molestiae sit dolor consectetur.', 'Eos molestiae et nam facilis quia ab aut maiores quia fugiat ex cupiditate id et ex eum velit dolores distinctio distinctio expedita qui eaque non.', 'Commodi vel esse aut voluptas cupiditate. Sit autem fugiat iure et facere inventore. Unde at dolore consequatur commodi ipsam. Delectus in molestiae animi molestiae in ea. Neque rerum tempora ipsam rerum et harum. Ea laboriosam sunt nesciunt architecto officiis. Facere dolor minima necessitatibus eaque inventore. Consequatur rem voluptatem dolorem. Quia optio quia temporibus dolorum voluptatem sit. Consequatur itaque voluptatum sequi illum. Repudiandae illum voluptatem porro. Aliquam earum enim accusantium assumenda necessitatibus veritatis qui. Dolor voluptatem et facere nihil facilis consequatur qui quia. Distinctio mollitia eos consequatur qui ut cum voluptatibus. Aut eaque aut nam sunt pariatur quaerat. Occaecati modi tempora aliquam voluptatibus esse perspiciatis repudiandae sed. Molestiae praesentium dolorem corporis eligendi vel ut. Beatae aut dolor dolores possimus qui alias. Nobis dolor molestiae voluptatem totam. Voluptas saepe sunt inventore sunt. Et consequatur labore quam. Exercitationem consequatur laudantium inventore cumque et ratione sed. Ut placeat velit assumenda corrupti sed eum. Modi enim quis inventore nihil.', '1.png', '', 1, '2022-01-22 10:49:34', '2022-01-22 10:49:34'),
(5, 'Odit at corporis iure.', 'Harum soluta omnis non quo porro nihil ea nihil et nostrum magni reprehenderit explicabo odit maxime asperiores sunt veniam rem numquam ut aperiam voluptas itaque velit neque veritatis esse adipisci vel et nihil et maxime autem autem et omnis.', 'Nesciunt autem temporibus veniam numquam atque. Corrupti aut rerum consequatur qui impedit nostrum dolorem. Error eius nostrum dolores nihil. Est iusto ut vel quo deleniti illum iste. Aut nemo quibusdam facilis ad modi vero fuga voluptatem. Expedita exercitationem quasi et explicabo. Sit molestiae eum iusto dignissimos sed et enim. Doloribus fuga blanditiis et ipsam laborum ea accusantium optio. Perspiciatis vel dolore esse unde sunt. Quis dolore sed ratione quod sed consequuntur repellendus et. Voluptatem neque vel quidem quasi. Quis doloribus est aut quia dicta. Nisi quae et maiores ut vitae. Enim quasi voluptatum hic harum. Optio incidunt non maiores pariatur cumque ut et. Et omnis et voluptas saepe molestiae maiores assumenda eum. Quisquam molestiae quod omnis qui sed. Sint quas non fuga vero voluptate odio. Aut corporis voluptatem in tenetur provident architecto.', '2.png', '', 1, '2022-01-22 10:49:34', '2022-01-22 10:49:34'),
(6, 'Nisi id ex est modi.', 'Porro id animi facere illo autem quibusdam omnis perferendis vero vitae ipsum totam ad cum et blanditiis eligendi a quis sint delectus ratione voluptates cum molestiae non iusto libero.', 'Qui voluptatibus et nam. Corrupti aut minima nisi velit. Voluptates expedita suscipit sint sapiente quaerat eum facere dolores. Rem officiis est ea esse tempora dolorem. Veniam ipsum sequi eos vitae. Sit beatae dolores est in. Molestiae id architecto quis. Et necessitatibus eos ut quis. Nobis corrupti dolores eum qui fugiat et. Optio deleniti qui voluptate sapiente doloremque sit. Sint itaque id illo optio saepe ratione. Et consectetur ullam temporibus qui rerum quis. Accusamus vero eum quae dolorem sequi unde. Molestias consequatur aliquid et quam eius.', '1.png', '', 0, '2022-01-22 10:49:34', '2022-01-22 10:49:34'),
(7, 'Consectetur nesciunt quos aut et quos similique.', 'Praesentium vel et sunt et ut qui nobis vero quidem quo ullam est temporibus expedita perspiciatis aut consequuntur exercitationem distinctio enim minima non consequatur.', 'Molestiae vel aliquid quas dolores. Modi excepturi ut est ipsum. Qui asperiores et labore totam cupiditate facilis. Saepe consequatur corrupti tempore sint neque quo. Aut ipsa aspernatur soluta aut voluptates. Iure dicta sequi illum reiciendis. Dolorem autem excepturi voluptatum inventore cupiditate. Voluptas laboriosam libero et ratione laudantium nisi molestiae. Hic porro dolores aut. Ducimus officiis nobis voluptatem facere facilis amet enim libero. In aut est in sint. Ratione ullam quae quo adipisci ea est. Voluptatem aliquid veniam ducimus asperiores facilis maxime. Sunt veritatis voluptatem voluptatem odio. Et quia voluptate voluptas. Mollitia aut ipsam neque quod quis sint et. Veniam exercitationem vel quisquam doloribus earum quae. Neque consequatur sunt qui aut. Atque ut facilis ut amet ut perspiciatis veritatis. Cupiditate nihil consequuntur pariatur hic. Fuga doloremque nemo eius commodi id. Id et eveniet vero quam amet. Et nihil sed eius autem quis esse enim. In autem mollitia corrupti nesciunt ad quae et. Assumenda quae quia et voluptas. Dolorem aspernatur architecto et voluptatem qui. Autem sunt omnis rerum natus sit facilis. Aut perferendis deleniti laboriosam error eius sunt. Quidem aperiam qui et officia modi doloremque. Veritatis est inventore et dolorem illum. Repudiandae est esse ea similique cumque ex nihil. Aut voluptatum fuga at. Quia necessitatibus aut possimus tempore eveniet. Dolorum explicabo qui nobis iure id esse est.', '4.png', 'nalchik', 0, '2022-01-22 10:49:34', '2022-01-22 10:49:34'),
(8, 'Quasi et cumque quasi.', 'Consequatur et et et voluptatem ducimus porro praesentium esse et voluptates rem harum sed sit et doloremque repellat laboriosam provident sed aliquid ut quasi quo.', 'Deleniti laudantium eos dolore totam quis. Eligendi ad quae fugiat ut quae. Reiciendis voluptates minima quae voluptas deserunt suscipit. Fugit accusamus culpa qui quis odit occaecati. Sed perferendis earum id porro sed saepe voluptatem. Qui minus qui enim quia a aspernatur. Architecto assumenda enim quam molestiae. Et enim cumque id voluptas quam illo dolor. Sint et iste harum illo corrupti molestiae. Cupiditate corporis illum quam accusantium. Minima magni odio fugit itaque. Magni nulla libero sit. Quidem rem omnis eos facilis ea et. Sint laboriosam aut est aut debitis. Voluptate consequuntur molestiae voluptate facere reprehenderit similique dolores. Molestiae consequatur est sit culpa explicabo accusamus dolores eveniet. Qui dolores et quod cupiditate ut deleniti quam qui. Velit et sunt veritatis enim sed distinctio voluptas.', '5.png', 'nalchik', 1, '2022-01-22 10:49:35', '2022-01-22 10:49:35'),
(9, 'Ex magni ea assumenda.', 'Dolorum aliquid aut magni id placeat natus cum saepe maiores similique ratione ipsum rerum et necessitatibus tempora repellat id.', 'Cum reiciendis dicta ullam sit omnis. Aut sunt itaque est unde. Modi quo sequi magni. Tempore blanditiis odit eos explicabo sint. Nisi qui expedita iure laboriosam itaque debitis. Sit aut est blanditiis earum est. Sint quas voluptas quisquam. Quas repellendus alias ut iste nihil. Quo aut id laborum ut. Maiores adipisci quo sunt ad quo. Dicta esse eveniet ab tempore enim id. Quisquam architecto qui iusto doloremque et. Tempora voluptatum accusantium maiores qui quo dolorem eaque. Hic sed aliquam velit dolor voluptatem qui sapiente hic. Eligendi labore ipsum debitis dolorum.', '3.png', 'moscow', 0, '2022-01-22 10:49:35', '2022-01-22 10:49:35'),
(10, 'Possimus eligendi quis atque et et magni.', 'Sit dolor fugit expedita eum odit hic dignissimos eos dolor odio expedita ut quod sed dignissimos aut.', 'Nam autem corporis quia. Occaecati molestias reiciendis molestiae et reiciendis. Doloremque ipsa debitis minima voluptatibus dolore. Maiores necessitatibus voluptatem accusantium nihil. Eligendi debitis qui error corrupti. Sit facere fuga velit vel non. Dolor ut voluptates deserunt quibusdam. Voluptatem est rerum accusantium officiis recusandae repellendus. Velit quasi laborum voluptas facilis. Ullam cumque exercitationem quo animi. Et corporis et nulla et. Libero odit qui dolorem sit quia quidem ea. Est excepturi dicta debitis. A quae quia sit laudantium ut perspiciatis. Architecto officia tenetur blanditiis sed eligendi. Esse perferendis maiores et odit ratione odio. Et cumque recusandae distinctio cum. Cupiditate dicta mollitia qui libero. Dolores provident ut minus rem et. Non porro eum sunt iusto. Dolor iusto accusantium accusantium explicabo maxime. Ipsa et sit sed rerum quasi animi rem. Laudantium saepe unde pariatur quod dolore ab. Accusamus ea et tempore sunt corporis omnis est. Quis ut voluptate distinctio fugiat maiores repellat nobis. Voluptatum dicta esse quo beatae est sit est eum. Commodi eum amet iusto dolores dolor qui. Mollitia quis reprehenderit dolores ut odit. Id non porro quis eaque ipsa culpa. Quibusdam sed et iusto nulla voluptatum dolor nostrum ut. Voluptatem culpa doloremque quasi fugit fuga a doloremque.', '1.png', 'nalchik', 1, '2022-01-22 10:49:35', '2022-01-22 10:49:35'),
(11, 'Dolore quis quam expedita doloribus explicabo accusantium consequatur tempora.', 'Eius in ut quia sequi autem maiores consectetur hic minima iure officiis dicta est amet fugiat quaerat minima non optio eos ex nam officia minima nulla vel qui ipsa voluptatibus ut voluptatem et.', 'Rerum fugit qui atque dolores sequi est voluptas. Error sit dolores illum ea distinctio qui amet voluptatem. Ipsa et sit ad voluptates veniam repudiandae sint. Nihil nesciunt voluptas enim autem repellat est. Quibusdam ut quaerat officia officia quos ut. Voluptate vero quia necessitatibus praesentium ea laborum. Rerum aut dolor perspiciatis cumque rem nisi. Animi sed ad dolor et ut eos. Corrupti sit recusandae ad et corporis. Architecto tempora hic similique id. Blanditiis ducimus quas ut incidunt quasi quis. Officia quod consequatur beatae autem quia est quos. Qui praesentium voluptate laboriosam quod et aut sunt architecto. Doloribus veniam sint iste. Quae quibusdam et quibusdam cumque qui mollitia dolorum. Quasi suscipit saepe et molestiae. Laboriosam cum ullam consequatur in iusto dolores. Eum ut quia quae et. Tempore eos architecto totam ut. Sit earum deserunt totam a delectus eveniet ut magni. Non facilis deleniti neque veritatis libero facilis. Reprehenderit eum vero quidem. Quod ipsa sit reiciendis consequatur reprehenderit. Dolorem officiis aliquid aut aut est. Tempore ut saepe et aliquam consequatur est dolor. Eius sed dolor tempora est facilis distinctio libero occaecati. Ut assumenda praesentium sunt possimus ullam aut.', '3.png', 'moscow', 1, '2022-01-22 10:49:35', '2022-01-22 10:49:35'),
(12, 'Quis explicabo quia voluptatem iure.', 'Eaque qui occaecati et esse aut minus sit vero non excepturi consequatur similique reprehenderit ea consequatur illo culpa cum veniam saepe et qui sit natus autem debitis.', 'Exercitationem tenetur cumque quo tenetur. Saepe sint doloremque molestiae voluptates. Quaerat tempora omnis incidunt ab voluptatem rerum. Aut ipsa optio aut. Eveniet illum pariatur modi commodi. Sit excepturi ut eos velit. Similique beatae velit sed nihil error et aliquam. Ipsam nulla consequatur repellendus voluptatibus aperiam. Alias necessitatibus in cum eligendi tenetur velit non. Neque illum earum saepe est dolore eaque quos. Similique animi culpa recusandae nisi asperiores ut quidem. Aliquam animi ut blanditiis aperiam vitae tenetur est fugiat. Unde incidunt et voluptatem amet numquam et. Labore nam quae aut dolores. Accusantium ad ratione rerum ex dolorum expedita est.', '3.png', 'nalchik', 0, '2022-01-22 10:49:35', '2022-01-22 10:49:35'),
(13, 'Sit sunt et quia.', 'Aut perspiciatis repudiandae rem rerum natus eius et quo omnis eum sapiente nostrum qui quaerat sunt laudantium cupiditate et ea.', 'Dolorum molestias esse dolores harum quo. Molestiae blanditiis aperiam iste. Fugiat repellat natus et voluptatem ducimus nulla eveniet voluptatum. Ea voluptatibus esse illo aut beatae quo. Rem doloremque similique aspernatur neque molestias. Repudiandae porro distinctio unde. Aut est architecto quia debitis optio. Exercitationem aut error sunt ut molestiae minus dolorem temporibus. Sit fugit consequatur quae dolor sit. Est iste doloremque inventore atque eum saepe quam. Dolor laboriosam modi reprehenderit quia enim velit. Nam quod dolore maxime quibusdam qui. Dolor quam quo quae cum quam. Quia ducimus quidem in occaecati et. Ut quaerat eum quidem veritatis praesentium deleniti. Quos id recusandae rerum quibusdam aut amet voluptatem sapiente. Animi architecto similique recusandae explicabo. Quod est velit fugit est dolores mollitia. Officiis et voluptatem sunt sunt aut. Assumenda voluptate eos nisi et repellat. Et minima illum vitae sed maiores quis officiis sint. A accusantium et quis labore eos excepturi. Provident provident esse enim iusto. A ratione cupiditate ipsam corporis est est facere qui. Tenetur voluptatem vel explicabo est nemo. Iusto qui debitis earum vel consequatur. Et consequatur nemo labore ea voluptatem. Voluptatem et est non qui. Dolores expedita neque explicabo et dignissimos. Possimus molestiae facilis consequatur. Error ut non incidunt nulla in facilis eaque. Quasi quasi mollitia sapiente aut corrupti tempora omnis. Labore non ratione temporibus eum quis. Possimus maxime aut sed ullam. Maiores sapiente quaerat tempore ipsam.', '1.png', 'nalchik', 0, '2022-01-22 10:49:36', '2022-01-22 10:49:36'),
(14, 'Dignissimos magnam soluta ad est.', 'Ea sed aut commodi aut illum omnis repudiandae exercitationem et accusamus soluta nemo autem cumque omnis praesentium.', 'Dolores rem omnis et non. Voluptas eius necessitatibus reiciendis quibusdam corrupti deserunt aperiam. Accusantium enim reiciendis vero illum inventore. Exercitationem reprehenderit incidunt vel eligendi error. Aliquam sint modi et voluptatem quas aut. Facilis et eveniet quis quod. At nemo facere odit velit cupiditate omnis. Dolor sed numquam sint expedita inventore autem repellat. Quod aliquid rem saepe fuga magnam iusto. Earum temporibus dolores corrupti laudantium pariatur tempore aperiam. Fugit magni tempora deleniti officia sapiente. Eligendi quis iusto aut. Voluptas modi eum itaque labore occaecati veritatis. Id et expedita ut eum neque magnam. Aut maxime ut officiis adipisci molestiae et. Aspernatur quasi ab et sit voluptate illo quisquam sit. Consequatur est corporis nobis quidem. Voluptas pariatur in aliquam laudantium consectetur reiciendis. Repellat dolorum voluptate animi autem quasi et.', '2.png', 'nalchik', 0, '2022-01-22 10:49:36', '2022-01-22 10:49:36'),
(15, 'Ratione voluptatibus id similique et et.', 'Maxime ullam et ullam similique rem voluptatem ab ex odio soluta laboriosam repellat voluptatem sint rerum itaque eum atque praesentium.', 'Temporibus in delectus reprehenderit. Dolore expedita natus ratione enim. Sit officiis minus tempora maxime odio ut. Fuga explicabo minus autem. Non in suscipit molestiae. Ea illo quo et asperiores et. Suscipit ea impedit vitae veritatis inventore. Corporis est consequuntur expedita odio. Quasi doloremque est id. Commodi est cum ex quia numquam aut et. Odit quia omnis in pariatur fugit eos optio magnam. Sint aperiam eum quod id cupiditate. Nobis laboriosam voluptas commodi quas. Maiores quasi autem enim nostrum animi. Ullam suscipit laudantium quisquam aut ut possimus dolorum. Possimus molestiae esse sint id praesentium. Quis vel nostrum consequatur totam possimus. At quidem repellendus temporibus consequatur velit aut. Quia aut non et cupiditate. Reprehenderit libero impedit doloremque deserunt sint. Eaque consequuntur rem aliquam cum magni. Accusamus eos quae vel quia ipsum.', '1.png', 'nalchik', 1, '2022-01-22 10:49:36', '2022-01-22 10:49:36'),
(16, 'Quae voluptatum velit nulla.', 'Aut consequatur et illo suscipit dolor perspiciatis omnis et et dicta aut suscipit et voluptas laudantium in et vero cum eos et officia eius dolor omnis voluptatem.', 'Aut ad corporis voluptatem cum nisi commodi. Beatae eos necessitatibus recusandae quae aspernatur esse recusandae. Dolores sunt consectetur velit quisquam aut et ut amet. Adipisci dolore aut aut minus adipisci ipsam. Voluptas sint aut sit tempore nesciunt et qui. Veritatis explicabo libero molestiae accusantium odio. Est occaecati omnis tenetur nemo. Aut non occaecati pariatur enim. Officia voluptas odio aliquam rerum modi quia assumenda in. Velit recusandae molestias tenetur impedit non ratione hic. Quas laboriosam eius quae et corrupti accusantium. Ut odio inventore explicabo eum maxime aspernatur vitae et. Sit voluptas et tenetur est ipsa tempora consequatur. Minima enim aut sit unde. Ex voluptates voluptatem ratione est rerum. Cumque aut voluptatum sunt recusandae necessitatibus. Corporis accusantium corrupti esse molestiae delectus hic amet. Beatae ut aut aut cupiditate voluptatem laborum. Cupiditate quam hic soluta quo quia. In odit sed est aut. Sit nulla perspiciatis est in magni aut aut saepe. Dolorem in omnis enim laudantium eos aliquid deleniti. Laudantium qui consectetur occaecati qui mollitia. Quo perspiciatis est excepturi nostrum consequatur culpa. Neque voluptas culpa aliquam deserunt dolores. Minima ea eaque dolores eum tenetur rerum. Expedita est debitis magni nesciunt.', '3.png', '', 0, '2022-01-22 10:49:36', '2022-01-22 10:49:36'),
(17, 'Qui dolorem libero quia.', 'Et ducimus hic odio sed deleniti voluptatem illo et est id commodi rerum laudantium quis repudiandae quaerat est sapiente ipsa qui libero sit est.', 'Quaerat voluptates id alias minima qui. Doloribus ipsa repellat placeat atque voluptatibus. Voluptatem blanditiis illum sed et. Quis nobis aut laborum architecto doloremque ut corporis doloribus. Deleniti hic quas esse ea. Aut expedita ut doloribus eveniet. Assumenda assumenda nostrum natus autem voluptas voluptatem. Aut optio porro et voluptates et illum. Libero est rem reprehenderit. Voluptatem ea accusamus enim modi. Consequatur veritatis fuga voluptatem dolores. Omnis corrupti suscipit rerum est. Ullam tempore eveniet facilis impedit eos. Omnis corporis cumque aspernatur similique magnam. Rerum deleniti odio quia. Omnis quisquam voluptatum corporis non quidem. Asperiores a vel ad fuga aut tenetur voluptatibus. Harum necessitatibus incidunt expedita velit magni vel optio. Quisquam doloremque et in tempore odio temporibus quas. Nulla necessitatibus omnis omnis praesentium occaecati et et. Totam itaque asperiores consequatur sit. Molestiae magni earum delectus eligendi dicta vel nesciunt. Aperiam consequatur minima itaque pariatur expedita. Voluptatem consequatur aperiam explicabo. Aut consectetur dolor asperiores occaecati aut quo eos. Adipisci non magnam qui accusantium. Officia reiciendis qui adipisci enim aut.', '3.png', '', 0, '2022-01-22 10:49:36', '2022-01-22 10:49:36'),
(18, 'Doloremque saepe nobis ea sunt illum fugiat.', 'Qui quia sequi sed blanditiis nulla sunt possimus ut optio culpa et ipsa ducimus nam.', 'Tempora nisi ut quaerat nesciunt aliquam. Ex asperiores sint aut rerum accusantium aut. Expedita a quo esse. Vitae sunt totam et. Sint repellat doloremque provident tempore necessitatibus sit doloremque quo. Laudantium voluptatem placeat debitis excepturi ipsum possimus. Inventore illo quia quia eos illum fugit sit. Alias enim et nesciunt ipsum. Nulla qui quia aut quas iste exercitationem. Ut quod et aut ducimus. Placeat adipisci laboriosam similique iusto reiciendis. Et molestias quia accusamus. Unde molestiae qui non enim. Iste quas quia molestiae aliquid aut velit. Sit quo ut provident aut suscipit debitis exercitationem. Aut commodi quis illo omnis deleniti qui. Tenetur ducimus similique consectetur. Facilis quasi similique vel similique voluptate. Non omnis ex molestiae nobis dolorem et dolorum iste. Ad et voluptatem fugit aut. Reprehenderit similique illo et in velit itaque. Facere quasi saepe molestiae architecto sit. Vel dolorem magni natus assumenda. Eius ut est sit ut. Iusto necessitatibus dolores id porro. Hic ea non doloremque tenetur qui ea. Et ut dolorem repudiandae et veniam labore ea numquam. Voluptatibus quo magnam minima vel illum sapiente tempora. Voluptatem omnis dolorem molestias. Nihil et occaecati voluptate natus eligendi sed et. Qui voluptas aut ut hic quas maxime at. Unde earum nostrum quae ipsam iusto. Neque doloremque voluptatibus fuga incidunt quo magni qui.', '2.png', 'moscow', 1, '2022-01-22 10:49:37', '2022-01-22 10:49:37'),
(19, 'Ipsam velit et excepturi aut quia assumenda et.', 'Et occaecati ut necessitatibus voluptatibus debitis aperiam soluta officia voluptate maiores et quia aspernatur corrupti ut ex quod.', 'Ut voluptas debitis veniam fugit cupiditate minima aspernatur. Reprehenderit deserunt delectus ad. Nam dicta dolorem quia. In dicta non a error. Est ut iusto necessitatibus non est sapiente. Mollitia voluptas quod veniam aspernatur in quia deserunt. Eum voluptatem inventore eius est repudiandae. Ea illum aut harum asperiores nostrum fuga. Dolores recusandae alias consectetur aperiam in sapiente labore ut. Quam numquam fugiat aperiam assumenda velit veniam. Animi sit quia et nihil qui. Tenetur corrupti blanditiis et beatae et qui reprehenderit. Eos totam temporibus alias architecto. Est ipsam voluptatem consequatur magnam dolorum ratione nihil. Sapiente aliquid rerum deserunt placeat rem id.', '2.png', 'moscow', 0, '2022-01-22 10:49:37', '2022-01-22 10:49:37'),
(20, 'Est qui provident aut at a aliquam.', 'Repellendus dolore illum omnis quam ut quam sed dolorem voluptatem temporibus amet velit repudiandae.', 'Et et et sed fuga rem quis fugit. Autem qui qui iste sit voluptatem voluptatem impedit. Qui tempore voluptas molestiae magni. Non id fugit qui et nemo. Modi saepe est aut. Et rem illo est vero ex facere et voluptatem. Ea labore quae autem. Facere quia rem laboriosam cupiditate. Quam aperiam laboriosam quaerat dolorem nobis. Qui repellendus voluptas praesentium. Ipsum omnis id quas iste in voluptatem ut numquam. Consequuntur incidunt exercitationem maiores eius ex. Dolorem id fugiat in est deserunt repellat sunt. Autem ea non error aut laborum magni. Consequatur illo dolorum architecto est magni debitis nostrum quia. Cupiditate unde sunt itaque et error et molestiae. Ratione quam nihil modi ea. Velit cumque fugit dolorum incidunt eum. Labore nobis recusandae ut provident. Aperiam sequi vero aut qui. Sint dolor consequuntur est possimus numquam. Ea omnis architecto quibusdam sed. Est assumenda atque et minima magnam pariatur. Non provident exercitationem laboriosam ex molestiae voluptate. Ducimus sint ipsa id quia in. Quisquam provident excepturi non rerum labore. Labore temporibus accusantium nihil. Et ipsam quis quisquam delectus doloribus error sunt. Modi sed unde asperiores voluptates dolores provident placeat error. Repudiandae vel delectus est ut omnis omnis. Quod in voluptate quia ipsa unde ea consequatur id. Nulla molestias quia totam suscipit et accusantium quae. Nemo dolor cum enim nam provident aut eum.', '1.png', 'moscow', 0, '2022-01-22 10:49:37', '2022-01-22 10:49:37'),
(21, 'Dolores qui laborum et.', 'Aut libero quas non officiis occaecati provident corrupti omnis iste soluta omnis pariatur temporibus natus est enim incidunt eaque nostrum dolor quia velit et et culpa ipsam reiciendis quia ratione.', 'Voluptatum ab ut ad reprehenderit. Dicta et quae nihil consequatur totam. Aperiam voluptatem dolorum ipsa ex eaque dolore. Sequi iste nobis eum tempora porro nesciunt. Sint consequuntur voluptatum sunt iusto dolore. Qui vero illum assumenda voluptas. Quod quibusdam adipisci et expedita. Error maiores provident architecto. Quo omnis voluptas est in. Est ipsum qui autem id alias a et. Aliquid molestiae et possimus eveniet sed possimus. Qui quia beatae est ab. Assumenda tenetur et blanditiis assumenda qui nobis dolorum. Quas nihil vitae velit excepturi sapiente dicta deserunt recusandae. Consectetur quis suscipit rerum eos. Aspernatur eaque ut tempora. Dignissimos et et minus. Alias magnam facere suscipit dolorum maxime. Quam autem sed et voluptatem. Enim enim non velit et. Possimus quasi dolorem facilis perspiciatis. Accusantium quae aut quo nihil sint magni unde. Non aperiam voluptatum tempore qui. Est sint illum et tempora voluptas mollitia incidunt. Aspernatur aspernatur corporis quos ducimus. Ab voluptatem minima nulla in sapiente aut adipisci. Consequatur voluptatem recusandae reiciendis. Quam rerum iure dolorem exercitationem animi. Quo illum rerum aperiam qui aut inventore id. Est earum et est necessitatibus. Qui voluptatum debitis quisquam.', '2.png', 'nalchik', 1, '2022-01-22 10:49:37', '2022-01-22 10:49:37'),
(22, 'Porro omnis tempore et dicta amet.', 'Commodi rem rerum perferendis officia et veniam aperiam nobis et eum a officiis est eius quia rerum aut minus id voluptatem.', 'Sit distinctio magni quia beatae sunt vel. Eius nulla rerum omnis debitis perferendis. Est numquam dignissimos in qui minima. Voluptatum in itaque beatae sequi quia doloremque iure. Ipsum sunt tenetur quia sit assumenda illum. Et eum vel quia ut quis quibusdam vel. Optio consectetur qui quasi libero eaque amet quia. Exercitationem temporibus ratione quibusdam asperiores qui sed expedita sint. Quia doloremque aut voluptas. Ut libero cum rerum. Ea molestias ex velit consequatur voluptas consequuntur nobis est. Quia quidem quis cum necessitatibus esse ut temporibus dolorem. Ullam est beatae quis corrupti. Aut fugit autem rerum ut iure harum quis. Consequuntur dolorem iure quae qui. Rerum cupiditate aut accusamus sequi non nostrum. Et sequi suscipit cum suscipit perspiciatis velit. Perferendis laboriosam optio eos eaque. Alias eligendi iste saepe. Error eum incidunt voluptatem autem. Sequi iusto officia vel velit. Necessitatibus reprehenderit est architecto asperiores delectus cumque. Dolorum rerum cum sit consequatur laudantium non. Earum error aliquam blanditiis voluptatem. Earum rerum cum sint soluta nam qui. Harum aut dolores dicta ea. Qui a sed atque ipsum ea placeat. Consequatur adipisci architecto corporis repellat quia qui maiores sit. Dicta neque ipsum eius consequuntur maiores consequatur.', '3.png', 'moscow', 0, '2022-01-22 10:49:37', '2022-01-22 10:49:37'),
(23, 'Vero officiis corporis accusantium blanditiis eum.', 'Quia ut laboriosam unde laudantium vel provident dolorem ut nesciunt vel tempore voluptatem et officiis nostrum voluptas molestiae officiis.', 'Sequi corporis ut fuga mollitia vel aliquam. Assumenda vitae sequi iure beatae harum quo qui a. Magnam ipsum nisi officia non nemo quo. Vitae excepturi qui odio nesciunt eum autem. Recusandae est autem qui ad velit. Maiores maxime qui voluptatum eos mollitia rerum. Culpa dicta libero adipisci non aliquam. Est nobis nisi non voluptas quia minus. Dolore voluptas non doloremque asperiores veniam dolorem. Cum esse est quis ut. Et recusandae omnis dicta aut rerum. Excepturi ut at voluptas optio accusantium rerum. Vel sequi vel consequatur debitis. Tempore provident necessitatibus autem. Possimus sit in repellendus et soluta ut molestiae. Ad vel officiis facere fugiat dolores. Neque similique non iusto in. Sapiente eligendi repellat sunt aut. Voluptatem praesentium est soluta libero ab. Ut natus eos tenetur et aut distinctio. Voluptates et quam iste minus quisquam. Magni eveniet quaerat hic molestias animi porro tempore. Id in id id cumque eius iste. Omnis aliquam quod sequi est. Ipsa atque culpa enim. Minus laboriosam consequatur voluptas voluptates quae. Ea veniam ut accusamus. Eaque cumque iusto ex. Iure molestias ut omnis asperiores. Totam occaecati laudantium autem dolorum aperiam. Provident ut eaque molestias molestiae aut velit. Vero maiores expedita et saepe ea sunt iusto. Nobis incidunt itaque sed ratione consequatur minus ut. Reiciendis quam eius sit eaque est. Esse recusandae nam provident laborum optio. Maiores quam illo voluptatem et dolorem nihil.', '2.png', 'moscow', 1, '2022-01-22 10:49:37', '2022-01-22 10:49:37'),
(24, 'Facere aspernatur eum et ipsum sed possimus.', 'Qui et ut qui aliquam laudantium in officia quaerat et quae expedita rerum exercitationem reprehenderit officia esse saepe soluta saepe aut velit rem voluptatem occaecati explicabo aut quis quia.', 'Nihil laboriosam saepe iste sapiente recusandae. Ad atque quas ea alias. Est earum earum est numquam voluptatem omnis. Ut et quo nihil praesentium. Velit est ea animi exercitationem enim aut voluptatum quo. Aut totam sed in. Fugiat voluptates hic deserunt ea tempora sunt. Molestiae ipsa qui maiores ipsam nemo odio explicabo. Inventore voluptatem temporibus accusantium qui. Nostrum ut ducimus est. Recusandae maxime officiis mollitia qui quam deserunt est eum. Reiciendis quae et a nobis sequi. Et optio maxime voluptatibus nulla. Maxime qui sit at. Voluptatum ea ullam autem in ipsa. Natus voluptatum et consequatur illum et. Omnis omnis odio est voluptate. Accusamus cupiditate unde facilis voluptas. Quia esse amet nihil enim est ipsam et. Omnis corporis expedita deserunt eum ut fugit eum. Aspernatur in voluptates id et. Eligendi pariatur et eveniet rerum. Suscipit ad sint sapiente magni iste. Eos illo nulla qui in sunt. Quo nulla voluptatem quod rerum cumque aspernatur. Est libero qui et aut qui earum. Laboriosam ut possimus quod aspernatur error expedita earum. Laborum ullam error a culpa doloribus deleniti quos. Et beatae assumenda nisi soluta deleniti quidem. Impedit commodi molestiae molestiae ducimus fuga minima. Doloribus ut architecto id dolores ex corporis magnam ut. Pariatur consequatur natus voluptatem quos. Occaecati nobis cum ab necessitatibus quis sed. Qui aut dolore et qui similique. Eveniet sint odit aliquam est iure. Nihil corrupti et quia assumenda enim ea.', '4.png', 'nalchik', 0, '2022-01-22 10:49:37', '2022-01-22 10:49:37'),
(25, 'Vel consequatur quidem quo.', 'Nobis voluptatibus reprehenderit impedit delectus est commodi unde assumenda sunt quos qui impedit veritatis voluptatem.', 'Quaerat error rerum voluptatibus. Rerum similique eos neque at. Id quaerat voluptates totam doloremque. Ratione laborum explicabo autem praesentium beatae et porro. Veniam a placeat qui aliquid ratione pariatur cupiditate veniam. Ut voluptate doloremque doloremque et nesciunt magnam nam. Nemo sit recusandae reiciendis officia id. Pariatur ducimus autem perspiciatis omnis sint. Laborum quod quas explicabo distinctio. Natus sapiente illum ut voluptas. Error hic quia aspernatur assumenda est exercitationem. Explicabo sed ducimus dolore vitae. Id aut veritatis modi explicabo maiores amet. Quos molestiae soluta et enim. Labore maxime non perferendis saepe. Architecto adipisci voluptatem doloribus unde. Commodi laudantium velit sit consequuntur nostrum ea. Illo qui commodi dolorem consequatur ut ipsum nam. Et minima et aut nostrum voluptatem omnis laudantium ut. Sed corrupti ex asperiores. Ut deleniti consequatur nemo. Tempore nostrum facere porro aut asperiores. Dolore ipsam dolor libero non. Assumenda sed amet quo iure. Labore velit in totam esse fuga. Necessitatibus quae ut labore enim labore. Laudantium atque sequi eaque impedit facilis. Dolorum et fugit laudantium aperiam qui. Consequuntur ad esse laudantium molestiae recusandae. Esse nobis qui qui dolor.', '5.png', 'nalchik', 0, '2022-01-22 10:49:37', '2022-01-22 10:49:37'),
(26, 'Iusto sequi dolor doloremque illum accusamus consequatur doloribus iure.', 'Aspernatur sit est corrupti et enim qui odio molestiae dolor facere harum totam modi aut officia omnis magnam voluptatibus ab.', 'Expedita culpa autem iure deserunt. Praesentium voluptatum ducimus natus repellendus et molestiae ut. Est deserunt dolores quam necessitatibus quia iste placeat vero. Alias corrupti omnis corrupti voluptatem incidunt veritatis. Qui dolore ut alias illo mollitia. Sed vel dolorem consequatur nemo quod. Sit fugit sit quibusdam reprehenderit qui illum quia soluta. Praesentium nobis et consequatur ut tempore. Animi distinctio officia dolorem. Et et atque hic quo ducimus aut. Et harum eius eos itaque blanditiis. Dolores doloribus iure quo tempora quo. Voluptate provident vero nam consequatur aut sit exercitationem. Ut culpa sit dicta. Voluptatibus molestias quas illum natus maxime deleniti. Beatae temporibus ipsam laborum autem in odio. Dolores voluptate expedita consectetur deserunt. Sequi rerum quibusdam eveniet ut quidem. Odio accusantium aut at consequatur est quae. Doloribus labore quisquam id. Possimus ut suscipit aut architecto et amet. Suscipit voluptas error est ut commodi. Sit voluptas voluptate modi in iure. Commodi libero laboriosam repudiandae eum ut dicta. Rerum sed quia facere cupiditate incidunt cum. Vel pariatur eum quis et explicabo omnis iusto beatae. In quod dignissimos sapiente molestiae vitae ut debitis explicabo. Voluptatem quidem ipsum quo itaque sapiente incidunt et. Amet et commodi neque molestiae. Non quod sint repellat ea perferendis alias nesciunt. Odit et quis nobis quis quae. Quaerat omnis reprehenderit hic quam reprehenderit aliquid iste. Error fugiat rerum natus blanditiis aut alias dolor dolores. Qui enim distinctio molestiae assumenda aliquam iure nemo dignissimos. Ut tenetur et dolorum ut nihil est. Nam nobis molestiae est temporibus et sit fugiat et. Accusamus sunt libero sequi inventore quas alias odio.', '1.png', '', 1, '2022-01-22 10:49:38', '2022-01-22 10:49:38'),
(27, 'Maiores est magni tenetur ex quia.', 'Necessitatibus hic architecto vitae aut rerum omnis autem qui eos amet tempore eum voluptates laboriosam delectus aut doloremque et mollitia porro inventore deserunt qui sit in.', 'Quia perspiciatis quo laudantium et repellat molestiae. Libero similique dolorem et sint mollitia neque impedit. Deleniti facilis ducimus perferendis repellendus est consequatur aut. Sapiente aut qui earum et dignissimos dolorum dolor iusto. Ex itaque facilis cum nihil ducimus rerum. Ea consequatur in id. Minima quo fuga consequatur sunt est ut explicabo dicta. Est sit ut est dolor. In libero et vitae qui ut ipsam. Ut eligendi qui molestiae labore sint totam soluta. Alias inventore nihil et praesentium et fugiat ut. Assumenda eum qui pariatur qui. Est et vitae pariatur rerum natus sed aut. Sunt aut placeat exercitationem ratione qui. Maiores dignissimos ab maiores consequatur esse et velit aliquid. Velit earum est autem. Laudantium fuga laudantium reprehenderit quia saepe officia eum. Repellendus est harum consequatur velit est est. Qui beatae quia nam voluptate. Ut quisquam veniam eos molestiae impedit. Eos dolor aperiam aperiam numquam amet et dolor dignissimos. Sit sunt et nesciunt. Distinctio quaerat aut quos aperiam non. Vel dolor facilis velit vero tempora doloremque a. Neque libero quis quaerat velit velit sequi. Omnis numquam excepturi ut ut molestiae ratione enim qui. Ipsa necessitatibus voluptas sit at explicabo. Repudiandae temporibus quas nulla magnam aliquam aut culpa. Rerum eos error quam. Nostrum aut quas laboriosam quam ut eligendi debitis quis. Incidunt laboriosam molestiae nostrum ullam. Qui aliquam culpa expedita corrupti. Velit nostrum perferendis id consequuntur cum aut. Itaque atque maxime cumque ut assumenda laborum.', '2.png', '', 1, '2022-01-22 10:49:38', '2022-01-22 10:49:38'),
(28, 'Ea qui adipisci.', 'Ad et in architecto nemo aperiam ipsam qui nihil totam qui excepturi voluptatem officiis qui id ipsam facere voluptas dolor rerum qui molestiae dolor.', 'Non sed consequatur architecto laudantium corrupti consequatur eligendi. Et et assumenda repellat aliquam quibusdam. Neque qui quia hic est in ipsam. Magni labore qui saepe magni consequatur dicta voluptates. Nihil omnis nisi et et. Minima tenetur odio quam quibusdam. Quae rem libero enim. Porro omnis sit aut eum quibusdam. Et impedit rerum necessitatibus officiis distinctio neque similique. Voluptates expedita quidem veniam dolorum est atque error. Expedita odit voluptas quos sequi velit et harum. Qui voluptas mollitia quia eos qui. Qui excepturi aut est quasi doloremque. Incidunt vel dolorem sequi vel et quasi. Earum eum adipisci magnam qui impedit molestiae tempora. Laboriosam temporibus ut impedit similique et aperiam unde. Sequi at porro sunt aut iure sed. Eius quis saepe sequi consequuntur doloribus cupiditate. Omnis nobis nemo et quam qui architecto voluptas. Quia nulla quibusdam praesentium ut. Qui reiciendis voluptatum ducimus maxime. Magni officia voluptate assumenda qui. Illum et quibusdam quod est iusto aut consequatur. Dignissimos deleniti et ut est magni nobis omnis cupiditate. Incidunt soluta et qui consequuntur est totam. Temporibus enim neque eum ullam. Inventore et fugiat rerum voluptate quia explicabo. Voluptatem iure voluptatem in et nihil mollitia et. Deserunt quidem doloribus consequuntur ab. Voluptates sed non voluptatibus culpa quo eius voluptas. Enim id porro ex. Voluptas animi fugiat earum et et est. Dolores quas cum quos. Occaecati ducimus et vel ullam consequatur.', '4.png', '', 1, '2022-01-22 10:49:38', '2022-01-22 10:49:38'),
(29, 'Est asperiores adipisci eaque.', 'Consequatur qui impedit autem maiores mollitia nihil rerum culpa assumenda vero autem non natus iste voluptates hic a iure vero expedita nam omnis qui illum.', 'Possimus cupiditate aliquid dolorum unde. Culpa iste cumque placeat ut. Officiis ullam nam sit suscipit numquam assumenda. Modi minus voluptas non aliquid. Occaecati qui qui sapiente ex voluptas architecto laborum quisquam. Magnam nemo qui unde a. Fugit distinctio voluptatum quibusdam quo dolorem. Nemo magni molestiae qui est voluptates. Iusto aliquam dignissimos rerum ratione nobis quis. Tenetur nihil sequi ipsa dolores molestiae sed enim minima. Aut facere et est atque est. Vel molestiae quia ut officiis.', '1.png', 'moscow', 1, '2022-01-22 10:49:38', '2022-01-22 10:49:38'),
(30, 'Excepturi fuga voluptates fuga deserunt.', 'Quae est suscipit est sint temporibus quo ex omnis asperiores aut sed eum qui rerum omnis maxime aperiam.', 'Hic ex amet itaque id soluta. Et distinctio consequuntur modi et a quod. Quia autem quo est neque deleniti. Consequatur nam enim in sed. Et tenetur voluptatem animi veritatis suscipit dolorem. Perferendis et vel molestiae in sit. Vel quae maiores eos quia consectetur. Molestiae ut accusantium facilis assumenda corrupti sunt alias. Itaque quis temporibus nisi quas nesciunt sed similique. Aliquam asperiores cum eaque eum. Omnis expedita velit id vitae deleniti voluptates sit non. Voluptatem omnis excepturi quo aut quia exercitationem. Voluptatem sit tempora voluptatem deserunt. Earum recusandae omnis velit commodi consequuntur autem enim ipsam. Consequuntur ut et sit ipsa nobis repellat omnis. Commodi cumque incidunt voluptatem illo asperiores molestiae et. Aut qui et dolorem molestiae alias eos labore. Est accusantium animi iusto aliquam. Culpa voluptatibus sit dolores est. Temporibus quia explicabo voluptas sunt alias quia eveniet. Assumenda doloribus beatae occaecati voluptatem. Ex similique ut aut non et deserunt. Dolorum tempora vel est dolore voluptatibus. Aut est nesciunt optio sit. Alias impedit iste omnis. Quis quis dicta esse incidunt aliquam.', '5.png', '', 1, '2022-01-22 10:49:38', '2022-01-22 10:49:38'),
(31, 'Laudantium maiores officia tempora voluptas repellendus velit.', 'Voluptas quod error totam quibusdam voluptatum a quo sunt aut saepe quam similique quaerat autem corrupti ipsum repudiandae ut eveniet et commodi ipsa officia et eveniet est sequi vel qui temporibus enim adipisci in.', 'At a eos velit illo a similique rerum. Aut officia magni modi laudantium aut et. Officiis delectus rerum quia eaque excepturi veniam molestias. Nam in nesciunt illo quaerat sint veritatis qui. Earum ut enim enim quisquam voluptatibus reiciendis. Et quia et et. Soluta amet dignissimos nemo ipsa error. Quos qui nemo repudiandae soluta modi. Temporibus facilis facilis aliquam quas deserunt sed quia. Delectus et inventore velit eum sint consequatur non et. Distinctio fugit in nam illo omnis. Quam ut voluptate omnis consequatur.', '2.png', 'moscow', 0, '2022-01-22 10:49:38', '2022-01-22 10:49:38'),
(32, 'Est quos facere debitis.', 'Suscipit consequatur nisi nulla aut veritatis eum pariatur impedit dolores officiis omnis rerum aut animi eligendi inventore ullam harum excepturi et tempore consequatur.', 'Nam dolor voluptas vel veritatis consectetur. Porro labore voluptas nisi ea quaerat velit ab dolorum. At aspernatur cum ex. Excepturi mollitia et aperiam sint corporis quia. Nulla voluptatem voluptatem dolorem distinctio et eius. Ab fugiat non omnis sapiente beatae laboriosam voluptatem. Vitae omnis voluptas nostrum delectus voluptas rerum quia. Adipisci aut veritatis beatae. Beatae aut sed aut dignissimos vel incidunt et. Voluptate adipisci molestiae excepturi fugit laborum. Id quasi laborum quos eveniet et. Dolores sapiente incidunt occaecati et dolores dolores. Ut et ea qui consectetur sint esse quia. Pariatur voluptas dolor consequatur ut iure atque. Deleniti sapiente aut tempore. Voluptatem consequatur velit atque eligendi quia. Ut aut occaecati ipsam consequatur libero. Saepe ut placeat eum itaque repellat voluptatem vitae. Vel iure officia id quae ipsa. Qui corrupti sit dicta laboriosam corporis non unde nihil. Alias minima officiis enim dolorum iusto quia sit. Perspiciatis rerum sed ab quidem. Aut totam ut qui. Omnis modi non quam praesentium unde quae placeat. Ea libero beatae laboriosam quaerat corrupti. Eos consectetur possimus doloribus animi. Nihil aut dicta omnis eos soluta suscipit cupiditate. Nihil quod ratione perferendis vel ipsum enim est. Ipsam eveniet eligendi at rerum neque architecto placeat. Minima aut veniam vitae ut excepturi. Voluptatem dolores error exercitationem error deserunt minima quis eaque. Quam quos unde animi aut velit. Accusantium minus ut laborum aut omnis error quos. Ex occaecati illo in. Omnis et eos cupiditate nihil dolores veniam. Occaecati maxime qui et inventore aliquam rerum. Ut impedit natus vero error deserunt.', '3.png', '', 0, '2022-01-22 10:49:38', '2022-01-22 10:49:38'),
(33, 'Sunt dignissimos nihil sunt aliquam.', 'Dignissimos atque est esse officiis non maiores esse sunt dolorum et et tempora facilis harum dolor et quod et.', 'Deleniti corrupti officia placeat est officia et sed. Voluptatem doloribus numquam omnis. Nisi aut quis quis repellat quidem et veritatis. Eaque ducimus reiciendis soluta vitae ullam. Voluptas et corrupti non similique voluptas totam qui. Totam omnis saepe similique necessitatibus a possimus. Aut quo porro odit et vel. Inventore aliquid ullam sequi architecto omnis numquam. Officia distinctio dolores quos repudiandae dolores. Et quo qui sed unde beatae. Officiis facere molestias et eum. Et in voluptatem modi modi sint. Non omnis sit laudantium aspernatur perspiciatis. Aliquid fuga corrupti aut velit laudantium voluptatem non. Molestiae corporis iste in ea. Sint aut veniam quo qui aut excepturi est. Rem laborum sunt et culpa autem impedit nihil.', '2.png', '', 0, '2022-01-22 10:49:38', '2022-01-22 10:49:38'),
(34, 'Sed qui et quia.', 'At dolor perspiciatis consectetur id laboriosam architecto tempora modi quod ducimus iure autem facere enim labore exercitationem accusantium.', 'Officia ut sit blanditiis maiores ipsum iste corrupti. Eos voluptatibus assumenda qui sunt ipsa quia. Dicta non quas laboriosam ad omnis. Consectetur itaque atque quas dolores ut et nulla. Minus voluptas laudantium enim quae. Consequuntur nulla molestiae quaerat cumque provident. Dicta vel qui mollitia autem provident vel qui similique. Culpa occaecati repellat ut quo accusamus. Qui animi maiores saepe. Recusandae consequatur rerum harum aut quod id quis. Cupiditate molestias quia voluptatum facilis cum. Autem sed perferendis at. Modi earum vel dolorum aperiam alias. Excepturi vel dolorum delectus doloremque rem et. Quaerat sed sint vitae similique vel. Reprehenderit vitae adipisci non aut velit ad. Eligendi labore incidunt animi labore voluptas. Perspiciatis sunt recusandae quibusdam ipsam eligendi dolores. Voluptas qui architecto consequuntur tempora laboriosam autem vel. Eos molestiae velit voluptatibus voluptas commodi nihil. Iure laudantium qui doloribus mollitia ea. Repudiandae repellendus et voluptatem ratione suscipit hic voluptatum culpa. Beatae dolore consequuntur nesciunt sit cum enim ut. Aliquam aliquid et quis in.', '5.png', 'moscow', 1, '2022-01-22 10:49:38', '2022-01-22 10:49:38');
INSERT INTO `news` (`id`, `title`, `about`, `text`, `picture`, `city`, `favorite`, `created_at`, `updated_at`) VALUES
(35, 'Dolores ut nesciunt consectetur molestiae.', 'Molestiae corporis consequatur illum sunt et nisi ut ut recusandae maiores minima iste debitis est repudiandae quae et.', 'Aliquam officia praesentium consequatur est pariatur qui. Voluptatum nesciunt reiciendis eos quo. Error aliquid incidunt dolorem occaecati. Et omnis qui temporibus commodi sunt autem. Possimus provident numquam et labore. Est voluptatem qui consequatur reprehenderit. Tempora sed numquam ullam consequuntur doloribus ad alias ut. Assumenda fuga cumque modi quis quas. Dolore corrupti non pariatur fuga aut. Fugit beatae delectus sit est nisi aliquid. Quia cupiditate eum omnis et perspiciatis voluptate impedit. Voluptatibus omnis est est qui voluptas sed veritatis. Aut ea optio minima ullam architecto optio. Saepe itaque maxime molestiae et. Est ut delectus possimus omnis totam qui. Unde modi et est molestias est. Incidunt iusto rerum expedita labore. Saepe ab voluptates amet nobis esse. Sapiente fugit molestias et amet. Voluptatem corporis esse facilis in sequi aspernatur beatae. Nesciunt cum voluptatibus autem dolores tempora aut impedit magni. Nihil unde sint est officiis nisi itaque est. Expedita iusto perspiciatis inventore corporis consequuntur quaerat temporibus. Quis perferendis vitae modi sequi qui beatae. Id quos dolore nemo omnis quis alias. Eos ullam repellat aperiam et veniam eius. At eos sint pariatur vero quia nostrum. Quae velit corporis totam molestiae aliquam.', '2.png', '', 0, '2022-01-22 10:49:38', '2022-01-22 10:49:38'),
(36, 'Quo molestias animi officiis.', 'Id blanditiis sed velit ut doloremque ullam porro ullam et quis id deleniti aperiam quaerat temporibus accusantium rerum enim qui quo.', 'Alias sed inventore dolor labore modi. Id molestiae cupiditate quod similique voluptas consectetur non. At ut quasi maxime eligendi. Quisquam ipsam totam perferendis dolore deserunt saepe. Velit perferendis quia et nisi voluptatem qui fugit. Molestiae voluptates consequatur aliquam velit id. Blanditiis fuga ut rerum non nostrum. Error et commodi in explicabo temporibus id. Eveniet animi incidunt consequatur eius quia et dolore aut. Facilis magnam facilis omnis voluptas. Est nesciunt quisquam aspernatur et et. Ea sed et voluptatum veniam sunt ut. Aut est facilis fugit doloribus veritatis. Et animi odit sapiente maxime magnam. Tempore quaerat rerum voluptates consequatur totam ut. Autem animi error illum enim. Ea soluta atque soluta voluptas in. Vel non optio maxime dolores voluptatem et. Impedit fugiat voluptate quam et. Provident odio amet consequatur explicabo. Aperiam placeat alias ut at quibusdam nostrum laudantium. Illum animi sed reprehenderit impedit nisi necessitatibus illo. Dignissimos eius tempore quia in. Accusamus possimus soluta odio soluta.', '3.png', '', 1, '2022-01-22 10:49:38', '2022-01-22 10:49:38'),
(37, 'Dignissimos dignissimos autem occaecati.', 'Et beatae ipsam ipsum incidunt vel suscipit fuga libero voluptatem et aliquid aut est doloribus.', 'Incidunt rerum nulla quia sint accusamus commodi. Dolor quos est nemo omnis. Praesentium consequuntur et amet ea illo quaerat culpa. Sit cupiditate possimus officiis sed est illum non. Et aut et ipsam dolorem voluptates et earum. Molestiae autem eum quia atque qui et totam. Ipsam quia fuga vel ea cupiditate sequi. Et magnam sed sunt nemo ducimus. Ad quis aut consectetur optio sed enim. Eum tenetur quia sint temporibus. Ut reiciendis fugit rerum. Amet natus asperiores odit fuga. Ipsa veniam quibusdam provident unde. Nihil non maiores quis impedit nulla qui et. Impedit sapiente a sunt eveniet enim. Ex qui delectus eligendi delectus non. Accusamus adipisci ratione facilis nulla. Ut atque accusantium suscipit ex quod. Illum recusandae numquam sit. Sint doloremque id quasi unde laboriosam et enim. Vitae incidunt dignissimos nam sed. Consectetur est voluptates ipsum.', '4.png', 'moscow', 0, '2022-01-22 10:49:39', '2022-01-22 10:49:39'),
(38, 'Minus excepturi delectus est dolorem id.', 'Eum magnam necessitatibus necessitatibus et corporis aut repudiandae quia ad fugit qui repellendus repudiandae voluptate.', 'Quis rerum eligendi dolorem quam dolorem. Ea suscipit cum consequatur et sunt et aut. Modi odit in eveniet sed et facilis beatae. Ex commodi explicabo quia quis alias animi officiis in. Qui placeat dolor amet incidunt officiis. Adipisci quasi voluptatem quae nemo blanditiis. Enim consequatur nemo non quidem aut fugit. Rerum ut velit voluptate quisquam quasi sed reprehenderit. Ullam id in ut unde quod. Laborum nulla sit ad. Vel voluptatem officia sed perferendis labore non. Qui ut corrupti voluptatum tempore minus et autem. Reiciendis dolorem magni quaerat qui. Doloremque reprehenderit recusandae et eos. Ut quos ut iste atque dolorum. Nesciunt rem nam exercitationem nihil veritatis numquam voluptas. Rerum eos iste aut ad aut qui molestias voluptatem. Ut expedita ducimus veniam quidem molestias. Sit nobis rem voluptatum excepturi. Rerum soluta officia ipsam in. Cupiditate sapiente excepturi quidem nam maxime. Ipsam provident aut omnis quam. Incidunt quo consectetur ab. Eligendi pariatur voluptates maiores quidem dolor. Dolore consequatur aut eum illo. Quo voluptas aliquam aut. Dolorem qui mollitia tenetur accusantium facere. Qui tenetur iste non ut praesentium. Delectus recusandae adipisci ipsa unde. Quod maiores dolor vero perspiciatis nisi. Et cumque assumenda quis saepe eligendi quisquam eveniet provident. Modi repellat quia rerum quia. Qui aut error sunt ea unde autem. Excepturi consectetur assumenda corrupti voluptate dolor aliquid. Dolor accusantium in debitis. Dolore sit voluptatibus natus quo. Ut eaque repudiandae voluptatum exercitationem. Itaque rerum aut ea. Est voluptatem ipsa ipsam suscipit sed. Omnis quos accusantium non et. Ullam ad voluptatem rerum qui suscipit cumque officiis. Laboriosam ullam quaerat in voluptatem laudantium itaque.', '5.png', 'moscow', 1, '2022-01-22 10:49:39', '2022-01-22 10:49:39'),
(39, 'Delectus repudiandae nihil neque dicta.', 'Dolor quo nobis pariatur molestiae quod quis corrupti harum corrupti eos nemo exercitationem laborum nesciunt tempora facilis autem.', 'Sed aspernatur nulla est id quidem. Asperiores repudiandae praesentium magni officiis. Neque consequuntur voluptatem minima non. Est quae recusandae ut autem fugiat. Sed vel est corrupti. Dolorem labore laudantium eos eaque. Veniam possimus voluptatum placeat. Aut neque natus similique. Fuga amet aut assumenda perferendis est voluptates. Error dolorem quis ipsum. Omnis eveniet magnam ut id officia laborum. Numquam tempore iure eveniet dolorum non impedit vel quia. Minima aut cupiditate eius ipsum accusantium iure aliquid. Dolore sed aperiam aut itaque et dolorum. Tempora eos cupiditate et magni ea deserunt. Tempore quo consequatur culpa distinctio. Facere cum ea ut iusto exercitationem maiores.', '5.png', 'nalchik', 0, '2022-01-22 10:49:39', '2022-01-22 10:49:39'),
(40, 'Porro officia ipsum odit ipsum velit consequuntur.', 'Sint error dolorem labore similique molestiae deleniti in debitis consequuntur qui inventore blanditiis vel non aliquam est quia et dolorum et minima.', 'Quia necessitatibus aut aut omnis sapiente reiciendis et. Doloremque non consequatur voluptas consequuntur aut. Voluptatum ipsam expedita voluptatem qui. Officia minima et repellat et rerum. Quibusdam esse id voluptas at. Quis natus eos et. In et odio qui et provident. Modi dolores alias voluptatem aut mollitia. Labore ad ut odit eaque. Occaecati consectetur ullam iste. Reprehenderit id velit ut rerum aut magnam ut. Praesentium ipsa deserunt quo aperiam cumque explicabo laboriosam. Sit ratione omnis odit iusto. Et placeat voluptatum id. Sunt autem quibusdam tempora velit at. Soluta facilis voluptas enim quas in tenetur. Quia sit eius eligendi facilis modi. Excepturi illum dolor id et laborum libero sit. In nemo sequi magni dolor. Voluptatem animi voluptatem nesciunt nisi natus aspernatur aut. Minima nam tempore eius. Veniam asperiores suscipit nulla voluptatem eum consequuntur. Mollitia dicta dolor quidem animi aut dolor ipsam. Ut autem vel aliquid temporibus optio. Voluptatem quia officia impedit. Laborum aut error consectetur illum ut ut beatae vel. Dolorem velit laboriosam est possimus qui deleniti. Quis vitae cupiditate architecto culpa ex aut facere.', '1.png', 'moscow', 1, '2022-01-22 10:49:39', '2022-01-22 10:49:39'),
(41, 'Rerum possimus deleniti ut voluptas.', 'Nihil voluptate id qui aut ea nostrum est tempore consectetur ut corporis ad vero debitis soluta consectetur fugiat.', 'Laudantium consectetur provident non exercitationem ducimus quas voluptate. Et consequatur architecto vel deleniti aut. Minus et molestiae voluptas doloribus aut adipisci quae. Enim unde repellendus at sed inventore tenetur sunt tempore. Quasi accusantium eveniet quia voluptas ut. Facilis ipsum est optio. Quis fugit suscipit enim sequi necessitatibus non optio. Dolore vel dolorem est et ipsa unde accusantium. Itaque aut nihil sequi laudantium. Nam corporis explicabo praesentium labore cumque ea architecto. Consequatur dolores nostrum distinctio impedit non voluptatem temporibus. Et voluptatem consequatur neque provident veritatis perferendis repellendus. Labore dignissimos voluptas dolor ab qui eum. Tempore minus debitis qui provident tenetur saepe ea. Alias id sequi porro enim hic. Excepturi beatae eius repellat vitae. Vero perspiciatis consequatur error facere dolore vel non magni. Non eos non id ratione sed labore. Odit ex temporibus et eos. Sit eius architecto voluptates quia sit ab officia veritatis. Molestiae maiores nulla fugit fugit qui delectus. Aut error ut ipsum dolores dolor. Recusandae quis accusantium sit sed in maiores sunt.', '5.png', '', 1, '2022-01-22 10:49:39', '2022-01-22 10:49:39'),
(42, 'Voluptatem voluptatem necessitatibus sed.', 'Aperiam incidunt quia veniam et enim expedita earum laudantium velit aut est fugit quae exercitationem ab ut rem.', 'Numquam eligendi quia facilis voluptatem. Et qui consequuntur dolorum ipsum culpa. Et ut et ea qui iusto et. Ut aut nulla dignissimos voluptate aspernatur laboriosam. Voluptas eaque totam reiciendis quasi quod et animi nostrum. Adipisci maxime quibusdam optio. Aliquam quia ullam voluptatibus. Nulla consequatur nisi repudiandae maxime sint et. Quae rerum eaque velit. Sed et velit provident. Qui necessitatibus error esse laborum voluptates eos. Officiis saepe eius quaerat deleniti in voluptatem. Qui qui quis libero earum. Ipsum praesentium harum veritatis at.', '1.png', 'nalchik', 0, '2022-01-22 10:49:39', '2022-01-22 10:49:39'),
(43, 'Sed blanditiis repellendus soluta labore labore.', 'Voluptatem voluptatem ut aliquid quas necessitatibus omnis architecto rem at aut quod doloremque itaque sapiente neque praesentium et id praesentium alias soluta necessitatibus rerum nulla alias voluptatem eos quo.', 'Repudiandae repellat voluptas itaque accusantium ratione maxime dignissimos. Occaecati corporis repellat praesentium expedita. Et atque dolores in ducimus recusandae repudiandae. Dolor aspernatur enim voluptatibus eum. Cupiditate sit nostrum quae necessitatibus dolorem quia et. Et est dicta quia est vitae. Voluptatem ut reiciendis laboriosam cupiditate. Omnis earum incidunt dolorum facere et error. Aut nostrum quod omnis laudantium quae quia molestias. Ipsa vero earum ullam aspernatur. Rem aut et consequatur molestiae reprehenderit. Eveniet sit vel rerum. Delectus quia voluptas ipsam dolorem. Quibusdam et fugiat quia eaque ipsam aperiam possimus. Aut placeat neque aut consequatur facere optio aut. Eos hic voluptatibus in deserunt et tempora. Et consequatur voluptas nulla a pariatur accusamus. Ut provident sapiente modi eos. Libero illo enim earum eum. Molestias perspiciatis ut dolorem.', '4.png', '', 1, '2022-01-22 10:49:39', '2022-01-22 10:49:39'),
(44, 'Omnis qui rerum rerum numquam architecto.', 'Tempore architecto ea et autem mollitia ducimus eveniet corrupti corrupti et sit sapiente architecto dolor et assumenda recusandae qui molestiae aut unde quia.', 'Et non ea aut dolorem nihil. Aperiam quis qui sit et suscipit. Est consequuntur earum omnis rem natus ipsam. Ipsa eos id repellendus. Molestiae optio inventore exercitationem et vero consequatur consequatur. Sunt sapiente similique rerum eaque porro. Quo alias ut nam distinctio omnis cum illum. Fugit laudantium rem facere suscipit nobis et rerum. Neque qui aliquam officia possimus. Maiores ut dolores sunt quos. Quam aut est reiciendis quas. Error voluptatem commodi voluptatum commodi harum est quas minus. Maiores omnis magnam et libero. Vitae quia nihil eaque omnis corporis.', '4.png', '', 0, '2022-01-22 10:49:39', '2022-01-22 10:49:39'),
(45, 'Omnis voluptatem dolorem et enim magni.', 'Saepe excepturi soluta laborum ducimus consequatur officiis amet itaque mollitia aut id accusamus accusamus ipsum cum dolor similique voluptate ea optio numquam asperiores corrupti qui et quis.', 'Molestiae porro qui non commodi et veritatis deserunt et. Quaerat ad et non recusandae. Mollitia ipsa consectetur omnis laborum. Suscipit accusantium fugiat dicta placeat id. Alias sed omnis laborum culpa sequi. Nihil accusantium blanditiis molestiae esse. Voluptas ex itaque est ut. Illum quidem nobis eos incidunt illum. Officia molestiae sint officia suscipit laborum dolor sed. Nobis aperiam beatae voluptas iusto in autem voluptatibus. Sint ut ipsam consectetur suscipit. Rerum quia deserunt corporis deserunt dolorem magni. Asperiores pariatur ratione quia natus similique non. Aut non et quo reprehenderit perspiciatis sequi nihil doloremque. Sit accusamus animi ea numquam ratione optio magni. Quisquam aut quo modi. Officiis sit dolore quam possimus quas. Occaecati tenetur eaque eveniet rerum. Magnam inventore unde enim enim neque recusandae sapiente. Dignissimos et pariatur officia. Fugiat itaque qui consequatur praesentium cumque odit. Sit et eum dolores et non. Quo sint animi error nemo.', '5.png', '', 0, '2022-01-22 10:49:39', '2022-01-22 10:49:39'),
(46, 'Molestias officiis est sit dolores.', 'Labore veritatis qui debitis ea unde et id fugit in et voluptas sequi itaque aliquid rem.', 'Tempora dolorum voluptate ratione aut. Nesciunt odio neque eaque porro quis vel labore eligendi. Veniam est repellendus sit iure temporibus nihil est quae. In tempora esse aut perferendis quod porro. Quam et culpa repellendus. Repellat et pariatur accusamus sed reprehenderit. Doloribus odio enim id vel quis. Voluptas voluptate sunt delectus et id explicabo vel. Blanditiis unde sit quo ut autem excepturi. Illo inventore unde molestias molestiae consequatur. Earum sunt nisi qui ipsa et totam. Asperiores laudantium ut quasi quae sequi corporis quia magnam. Eos aut impedit ab blanditiis non temporibus. Inventore maxime saepe culpa facilis sapiente accusantium. Quod nam perspiciatis illo ex molestiae minus dicta. Quae officiis sit voluptatem quos. Vel magni et dolores ut. Nesciunt ducimus a voluptatem ut totam. Voluptas aliquid commodi repellat. Cumque dolorem numquam mollitia repellat deserunt quidem. Soluta nostrum error aut eum nihil nihil dolores. Dolorem voluptas quo eaque distinctio velit perspiciatis. Eligendi cumque dolor perspiciatis eos cumque. Veniam quia sed similique non. Adipisci quas corrupti sed. Ducimus voluptates quam vel excepturi quia quia eaque. Deserunt ut dignissimos rerum. Eum ut eos provident odit quis. Eos facilis quia non dolore porro sunt. Vitae commodi vel doloribus id. Eaque iusto et voluptas vero. Deleniti tenetur et repellat. Eum id quaerat nostrum officia blanditiis. Doloremque omnis at aspernatur sunt. Possimus nisi temporibus ducimus. Et voluptatem praesentium consequatur et doloribus totam sint. Voluptate nostrum pariatur commodi est.', '3.png', 'moscow', 0, '2022-01-22 10:49:39', '2022-01-22 10:49:39'),
(47, 'Est voluptates asperiores quos iste rem adipisci.', 'Et cupiditate rerum est eum dolor et beatae nobis aut rerum sapiente porro est est eos dolore deleniti dicta similique quae et enim.', 'Ratione et veritatis voluptatem eos. Corrupti esse expedita perferendis placeat sit excepturi. Sit qui ut aliquam dolorem quia rem dolorum. Animi sapiente nobis quam vitae dignissimos. Quo minus dolor enim quia dolor. Architecto et molestiae sit. Quae libero accusantium quia minima aliquid. Maiores culpa quis ipsam eaque. Aut consequatur non qui atque doloribus explicabo ad. In ipsa soluta dicta odio quis est. Omnis natus molestias nam similique deserunt facilis nisi magnam. Numquam ratione omnis sit enim facere atque voluptas. Ea et veritatis omnis ipsum ut commodi dicta. Vel debitis quod aliquam dolores. Laudantium debitis tempora et ut cupiditate. Veniam odit rerum excepturi incidunt est excepturi harum. Est eum qui aut. Aut reiciendis mollitia sed illo ea enim. Rem sed neque in necessitatibus. Porro labore magnam magni consectetur modi nesciunt sit. Provident inventore consequatur et assumenda at suscipit. Vel sunt consequatur doloremque occaecati quidem aspernatur architecto. Voluptas provident enim est corporis ad. Perferendis voluptatem ad id reiciendis voluptas nesciunt. Excepturi odio quas deserunt nulla repudiandae distinctio. Et illum corrupti in magnam temporibus perferendis expedita. Quia dolores voluptatem voluptas nostrum. Magnam atque qui cupiditate dicta placeat non. In illo architecto id dolore aliquid. Sit eaque quasi sequi corrupti dolorum quia expedita dolores. Voluptas nobis quos voluptatem. Quia quos unde enim iure dignissimos. Quidem eum dolorem voluptatem dolorem aut voluptatum. Placeat id error sit officia. Sit excepturi numquam voluptatibus. Rerum sint harum alias incidunt ut amet praesentium.', '3.png', '', 0, '2022-01-22 10:49:39', '2022-01-22 10:49:39'),
(48, 'Omnis qui dolores.', 'Nobis iste omnis fuga nihil laborum voluptatum voluptas minima quia magnam minima quia ab inventore possimus vel expedita dolor minima quia pariatur voluptatem voluptatem consequatur.', 'Esse corrupti quas consectetur velit omnis ea sit. Voluptate et aut molestiae omnis. Veritatis sint eveniet doloribus error. Qui eos cum et et quae. Quisquam autem voluptatem minus blanditiis eligendi dolore ipsum. Debitis possimus eveniet eos voluptas quibusdam neque voluptas. Dolor numquam dignissimos quaerat id omnis hic ad. Libero veniam reiciendis dicta praesentium aut. Voluptate molestias cumque quisquam consequatur corrupti. Natus dolorem omnis qui modi aut error ea. Provident minima numquam eligendi dolorum. Qui facere quasi et non eligendi. Neque adipisci dignissimos est ex quas sed in. Id velit molestiae ipsa quos veniam. Molestiae molestias expedita sint dolorem nihil cum eius. Non aut quod et alias rem. Et qui nostrum tempora perspiciatis perspiciatis quo eveniet. Incidunt quia commodi ut minus blanditiis quos. Quaerat dolores fugit incidunt. Illum autem unde expedita cumque repudiandae. Ut ullam consectetur doloremque dolore velit. Vero rerum velit nam numquam. Vel quia aspernatur aperiam corrupti. Quia assumenda qui at quia hic. Sapiente quos animi fuga facere in odit saepe. Officiis sunt tenetur dolor quis eveniet. Voluptates libero veritatis corrupti. Error ut enim omnis sapiente molestias magnam ratione aliquam. Dolorum laudantium eum numquam expedita dolores. Non quos qui beatae et aut. Et et perferendis amet non. Dolorum suscipit est libero vero. Nemo aut eaque delectus in et cumque dolor ut. Sequi repellat eaque iusto similique quis eum. Vero voluptatibus natus perspiciatis in. Sunt quam atque hic fugit animi.', '3.png', '', 1, '2022-01-22 10:49:39', '2022-01-22 10:49:39'),
(49, 'Cupiditate magnam quibusdam officiis.', 'Et quia veritatis sint illo nemo non corporis enim modi ut necessitatibus delectus voluptatibus assumenda tempora quisquam maxime ducimus qui quas doloremque aspernatur amet a repellendus reiciendis sed sequi excepturi eaque vel et dolorem qui aperiam quaerat.', 'Error eos corrupti odio fuga dolores deserunt amet. Quidem laudantium aut qui eligendi repellendus provident et. Occaecati quos autem illo magnam sequi ipsum. Quo facilis labore quis enim ut cupiditate. Dolorem qui est ab in amet placeat. Quia et odit fugit necessitatibus et earum. Laboriosam eveniet atque omnis adipisci totam. In eligendi non sed totam facilis ut. Facilis sapiente dolore iste nulla mollitia. Dolore et corrupti aut nam vel odit dolor. Cumque laudantium doloremque architecto ipsa voluptas expedita. Non autem sapiente eligendi est cum odit. Molestiae quod voluptates qui qui omnis. Debitis a sed voluptatem at. Unde hic tempore voluptatem qui doloremque voluptas quod. Quisquam nihil dolores voluptatem doloribus. Ut aut eveniet aut porro. Magnam quaerat ipsam omnis voluptatem blanditiis. Rerum omnis repudiandae perspiciatis quia voluptatum. Dolores suscipit debitis ut cumque earum vero. Exercitationem debitis qui dolorem amet nulla aut. Suscipit aut suscipit voluptate omnis. Tempora quo perferendis at laboriosam aperiam officiis tempora. Qui eum corporis harum libero ab ex. Sit aut sint sed libero. Quasi dicta sed dolor reprehenderit atque. Omnis ipsa vitae quod velit earum. Eaque possimus praesentium sequi voluptatem dignissimos sed aut. Facilis atque quasi qui ex. Adipisci dolores sunt minus amet enim tempora. Itaque consectetur sed et et laborum. Dolor velit quasi ipsa adipisci voluptatibus odit aut. Eius ut id cum enim dolores optio sed.', '3.png', 'moscow', 1, '2022-01-22 10:49:39', '2022-01-22 10:49:39'),
(50, 'Quasi sequi a.', 'Sit est beatae earum quam delectus autem sit voluptas quibusdam ipsum est consequatur sunt animi sit aut sint sit quia laudantium cupiditate laudantium fuga qui unde rem repellendus consequuntur et dignissimos maxime qui odio.', 'Deleniti non voluptas autem aut occaecati est perspiciatis. Sit aut quas mollitia sed sint in sapiente velit. Repellendus quis similique fugit aut consequuntur necessitatibus. Omnis iure autem perferendis id. Corrupti eum id nemo dolores fugit occaecati. Qui ea laudantium sequi sed voluptas occaecati. Aliquam omnis reiciendis sit suscipit ipsam ut. Omnis illum est aut ipsa. Vero ea ea omnis laudantium minima et nisi. Suscipit accusantium consequatur architecto voluptatum sit soluta dicta. Ex exercitationem velit minus qui doloremque excepturi. Voluptatibus soluta autem error tempora. Et esse doloribus iusto. Sapiente distinctio consequatur illum totam ut esse voluptas. Quod ut est sit fugiat rerum autem odit. Occaecati odit cum aliquid fugit hic fugiat sequi. Laboriosam eos dolore autem porro et. Aut est sit blanditiis ratione aliquid laboriosam.', '4.png', 'moscow', 0, '2022-01-22 10:49:39', '2022-01-22 10:49:39');

-- --------------------------------------------------------

--
-- Структура таблицы `personal_access_tokens`
--

CREATE TABLE `personal_access_tokens` (
  `id` bigint UNSIGNED NOT NULL,
  `tokenable_type` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `tokenable_id` bigint UNSIGNED NOT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `token` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `abilities` text COLLATE utf8mb4_unicode_ci,
  `last_used_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Индексы сохранённых таблиц
--

--
-- Индексы таблицы `migrations`
--
ALTER TABLE `migrations`
  ADD PRIMARY KEY (`id`);

--
-- Индексы таблицы `news`
--
ALTER TABLE `news`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `news_title_unique` (`title`);

--
-- Индексы таблицы `personal_access_tokens`
--
ALTER TABLE `personal_access_tokens`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `personal_access_tokens_token_unique` (`token`),
  ADD KEY `personal_access_tokens_tokenable_type_tokenable_id_index` (`tokenable_type`,`tokenable_id`);

--
-- AUTO_INCREMENT для сохранённых таблиц
--

--
-- AUTO_INCREMENT для таблицы `migrations`
--
ALTER TABLE `migrations`
  MODIFY `id` int UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;

--
-- AUTO_INCREMENT для таблицы `news`
--
ALTER TABLE `news`
  MODIFY `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=51;

--
-- AUTO_INCREMENT для таблицы `personal_access_tokens`
--
ALTER TABLE `personal_access_tokens`
  MODIFY `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
